# Class config file for YOLOV5.
path: dataset 
train: images/train
val: images/val

nc: 365

names:
  0: N/A
  1: Sneakers
  2: Chair
  3: Other Shoes
  4: Hat
  5: Car
  6: Lamp
  7: Glasses
  8: Bottle
  9: Desk
  10: Cup
  11: N/A
  12: Cabinet/shelf
  13: Handbag/Satchel
  14: Bracelet
  15: Plate
  16: Picture/Frame
  17: Helmet
  18: Book
  19: Gloves
  20: Storage box
  21: N/A
  22: Leather Shoes
  23: Flower
  24: N/A
  25: Potted Plant
  26: Bowl/Basin
  27: Flag
  28: Pillow
  29: Boots
  30: Vase
  31: Microphone
  32: Necklace
  33: Ring
  34: N/A
  35: Wine Glass
  36: Belt
  37: N/A
  38: Backpack
  39: Umbrella
  40: N/A
  41: Speaker
  42: Watch
  43: Tie
  44: Trash bin Can
  45: Slippers
  46: Bicycle
  47: Stool
  48: Barrel/bucket
  49: Van
  50: Couch
  51: Sandals
  52: Basket
  53: Drum
  54: Pen/Pencil
  55: Bus
  56: N/A
  57: High Heels
  58: N/A
  59: Guitar
  60: Carpet
  61: Cell Phone
  62: Bread
  63: Camera
  64: Canned
  65: N/A
  66: Traffic cone
  67: Cymbal
  68: Lifesaver
  69: Towel
  70: Stuffed Toy
  71: Candle
  72: N/A
  73: Laptop
  74: N/A
  75: Bed
  76: Faucet
  77: Tent
  78: N/A
  79: Mirror
  80: Power outlet
  81: Sink
  82: Apple
  83: Air Conditioner
  84: Knife
  85: N/A
  86: N/A
  87: N/A
  88: Fork
  89: N/A
  90: Balloon
  91: Tripod
  92: N/A
  93: Spoon
  94: Clock
  95: Pot
  96: N/A
  97: Cake
  98: N/A
  99: Sheep
  100: Hanger
  101: Blackboard/Whiteboard
  102: Napkin
  103: N/A
  104: Orange/Tangerine
  105: Toiletry
  106: Keyboard
  107: Tomato
  108: Lantern
  109: N/A
  110: Fan
  111: Green Vegetables
  112: N/A
  113: N/A
  114: N/A
  115: N/A
  116: N/A
  117: Pumpkin
  118: Soccer
  119: N/A
  120: Luggage
  121: N/A
  122: Tea pot
  123: Telephone
  124: Trolley
  125: Head Phone
  126: N/A
  127: N/A
  128: Dessert
  129: Scooter
  130: N/A
  131: N/A
  132: Remote
  133: Refrigerator
  134: Oven
  135: Lemon
  136: N/A
  137: Baseball Bat
  138: Surveillance Camera
  139: N/A
  140: Jug
  141: Broccoli
  142: Piano
  143: Pizza
  144: N/A
  145: Skateboard
  146: Surfboard
  147: N/A
  148: N/A
  149: Gas stove
  150: Donut
  151: Bow Tie
  152: Carrot
  153: Toilet
  154: Kite
  155: Strawberry
  156: N/A
  157: Shovel
  158: Pepper
  159: Computer Box
  160: Toilet Paper
  161: N/A
  162: Chopsticks
  163: Microwave
  164: N/A
  165: Baseball
  166: Cutting/chopping Board
  167: N/A
  168: N/A
  169: Scissors
  170: Marker
  171: Pie
  172: Ladder
  173: N/A
  174: Cookies
  175: N/A
  176: N/A
  177: Basketball
  178: N/A
  179: Grape
  180: N/A
  181: Potato
  182: Sausage
  183: Tricycle
  184: Violin
  185: Egg
  186: N/A
  187: Candy
  188: N/A
  189: N/A
  190: N/A
  191: N/A
  192: Wheelchair
  193: Golf Club
  194: Briefcase
  195: Cucumber
  196: Cigar/Cigarette
  197: Paint Brush
  198: Pear
  199: N/A
  200: Hamburger
  201: Extractor
  202: Extension Cord
  203: Tong
  204: Tennis Racket
  205: Folder
  206: N/A
  207: earphone
  208: Mask
  209: Kettle
  210: Tennis
  211: N/A
  212: Swing
  213: Coffee Machine
  214: Slide
  215: Carriage
  216: Onion
  217: Green beans
  218: Projector
  219: Frisbee
  220: N/A
  221: Chicken
  222: Printer
  223: Watermelon
  224: Saxophone
  225: Tissue
  226: Toothbrush
  227: Ice cream
  228: N/A
  229: Cello
  230: French Fries
  231: Scale
  232: Trophy
  233: Cabbage
  234: Hot dog
  235: Blender
  236: Peach
  237: Rice
  238: Wallet/Purse
  239: Volleyball
  240: Deer
  241: Goose
  242: Tape
  243: Tablet
  244: Cosmetics
  245: Trumpet
  246: Pineapple
  247: Golf Ball
  248: N/A
  249: N/A
  250: Mango
  251: Key
  252: N/A
  253: Fishing Rod
  254: Medal
  255: Flute
  256: Brush
  257: N/A
  258: Megaphone
  259: Corn
  260: Lettuce
  261: Garlic
  262: N/A
  263: N/A
  264: Green Onion
  265: Sandwich
  266: Nuts
  267: N/A
  268: Induction Cooker
  269: Broom
  270: Trombone
  271: Plum
  272: N/A
  273: Goldfish
  274: Kiwi fruit
  275: Router/modem
  276: Poker Card
  277: Toaster
  278: Shrimp
  279: Sushi
  280: Cheese
  281: Notepaper
  282: Cherry
  283: Pliers
  284: CD
  285: Pasta
  286: Hammer
  287: Cue
  288: Avocado
  289: N/A
  290: N/A
  291: Mushroom
  292: Screwdriver
  293: Soap
  294: Recorder
  295: Bear
  296: Eggplant
  297: Board Eraser
  298: Coconut
  299: Tape Measure/Ruler
  300: Pig
  301: Showerhead
  302: Globe
  303: Chips
  304: Steak
  305: N/A
  306: Stapler
  307: N/A
  308: N/A
  309: Pomegranate
  310: Dishwasher
  311: N/A
  312: Hoverboard
  313: N/A
  314: Rice Cooker
  315: Tuba
  316: Calculator
  317: N/A
  318: N/A
  319: N/A
  320: N/A
  321: N/A
  322: Dumbbell
  323: N/A
  324: N/A
  325: N/A
  326: Dolphin
  327: Electric Drill
  328: Hair Dryer
  329: N/A
  330: Jellyfish
  331: N/A
  332: Lighter
  333: Grapefruit
  334: Game board
  335: Mop
  336: N/A
  337: N/A
  338: N/A
  339: N/A
  340: Spring Rolls
  341: N/A
  342: Rabbit
  343: Pencil Case
  344: Yak
  345: Red Cabbage
  346: Binoculars
  347: Asparagus
  348: N/A
  349: N/A
  350: Noddles
  351: Comb
  352: Dumpling
  353: Oyster
  354: Table Tennis paddle
  355: Cosmetics Brush/Eyeliner Pencil
  356: Chainsaw
  357: Eraser
  358: Lobster
  359: Durian
  360: N/A
  361: Lipstick
  362: Cosmetics Mirror
  363: N/A
  364: Table Tennis