# Generated by Django 5.0.6 on 2024-11-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_tag_remove_image_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(blank=True, to='images.tag'),
        ),
    ]
